services:

  backend:
    build: ./backend
    container_name: dsa_portal_backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/dsa_portal
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Klu@0505
    networks:
      - dsa_network

  frontend:
    build: ./frontend
    container_name: dsa_portal_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - dsa_network

volumes:
  postgres_data:

networks:
  dsa_network:
    driver: bridge